name: Android Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set API Keys
        run: |
          echo "KAKAO_API=${{secrets.KAKAO_API}}" >> local.properties

      - name: Gradle Test
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew assemble
